name: Build & Publish Extension

on:
  push:
    tags:
      - "v*.*.*"   # läuft, wenn du ein Tag wie v0.0.7 pusht

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Package extension
        run: npm run pack

      - name: Publish to Marketplace
        run: |
          npx tfx extension publish \
            --vsix package/*.vsix \
            --publisher ${{ secrets.AZDO_PUBLISHER }} \
            --token ${{ secrets.AZDO_PAT }} \
            --rev-version
